apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idp-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sayon-coder/idp-gitops.git
    targetRevision: HEAD
    path: charts/idp-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
